import turtle
wn = turtle.Screen()
wn.bgcolor('black')
turtle.color("blue")
turtle.right(65)
turtle.forward(150)
turtle.begin_fill()
turtle.backward(150)
turtle.color('red')
turtle.right(50)
turtle.forward(150)
turtle.color('yellow')
turtle.end_fill()
turtle.color('red')
turtle.backward(150)
turtle.right(155)
turtle.color('green')
turtle.forward(150)
turtle.right(120)
turtle.color('white')
turtle.forward(100)
turtle.backward(100)
turtle.left(240)
turtle.forward(100)
turtle.backward(100)
turtle.right(30)
turtle.color('purple')
for x in range(180):
	turtle.forward(1)
	turtle.right(2)
wn.exitonclick()
